In [25]:
import numpy as np
import nltk
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

In [26]:
f = open("cosine.txt","r")
text = f.read()
print(text)

Dog bites man. Man bites dog. Dog eats meat. Man eats food.


In [27]:
sentences = sent_tokenize(text)
i=0
stop_words = set(stopwords.words('English'))
filtered_sent = []
while (i<len(sentences)):
    tokens = word_tokenize(sentences[i])
    for token in tokens:
        if token not in stop_words and token.isalpha():
            filtered_sent.append(token)
    i += 1
    
print("FILTERED SENTENCE IS:- ",filtered_sent)    

FILTERED SENTENCE IS:-  ['Dog', 'bites', 'man', 'Man', 'bites', 'dog', 'Dog', 'eats', 'meat', 'Man', 'eats', 'food']


In [28]:
x = input("ENTER THE SENTENCE TO CHECK SIMILARITY:-")
tokens = word_tokenize(x)
filtered_sentence = []
for token in tokens:
    if token not in stop_words:
        filtered_sentence.append(token)
        

ENTER THE SENTENCE TO CHECK SIMILARITY:-man eats meat


In [29]:
print(filtered_sentence)

['man', 'eats', 'meat']


In [30]:
x = " ".join(filtered_sentence)
x

'man eats meat'

In [31]:
vectorizer = CountVectorizer().fit_transform([x] + sentences)
vectors = vectorizer.toarray()
print(vectors)

[[0 0 1 0 1 1]
 [1 1 0 0 1 0]
 [1 1 0 0 1 0]
 [0 1 1 0 0 1]
 [0 0 1 1 1 0]]


In [32]:
cosine_similarities = cosine_similarity(vectors)[0][1:]
print(cosine_similarities)

[0.33333333 0.33333333 0.66666667 0.66666667]


In [33]:
similar = np.argmax(cosine_similarities)
print("SENTENCE MOST SIMILAR TO THE USER QUERY IS:-",sentences[similar])

SENTENCE MOST SIMILAR TO THE USER QUERY IS:- Dog eats meat.
