In [2]:
import nltk
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
import numpy as np

In [3]:
train_text = ['just plain boring',
             'entirely and lacks energy',
             'no surprise and very few laughs',
             'very powerful',
             'the most fun film of summer',
             ]
train_label = [0,0,0,1,1]

test = 'predictable with no fun and no energy boring'

In [4]:
def preprocess(text):
    text = re.sub(r'<.*?>','',text)
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word.isalpha()]
    stop_words = set(stopwords.words('English'))
    tokens = [word for word in tokens if word.islower() not in stop_words]
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    return ' '.join(tokens)

In [5]:
for i,words in enumerate(train_text):
    train_text[i] = preprocess(words)
train_text    

['just plain bore',
 'entir and lack energi',
 'no surpris and veri few laugh',
 'veri power',
 'the most fun film of summer']

In [6]:
test = preprocess(test)
print(test)

predict with no fun and no energi bore


In [7]:
count_vectorizer = CountVectorizer(stop_words="english")
train = count_vectorizer.fit_transform(train_text).toarray()
features = count_vectorizer.get_feature_names_out()
features

array(['bore', 'energi', 'entir', 'film', 'fun', 'just', 'lack', 'laugh',
       'plain', 'power', 'summer', 'surpris', 'veri'], dtype=object)

In [8]:
train

array([[1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [9]:
test = word_tokenize(test)
test

['predict', 'with', 'no', 'fun', 'and', 'no', 'energi', 'bore']

In [10]:
tv = [0 for i in range(len(features))]
for i,idx in enumerate(features):
    if idx in test:
        tv[i]+= 1
        
tv        
    

[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

USING NAIVE BAYES

In [11]:
model = GaussianNB()
model.fit(train,train_label)
print(np.array(tv).reshape(1,-1))
model.predict(np.array(tv).reshape(1,-1))


[[1 1 0 0 1 0 0 0 0 0 0 0 0]]


array([0])

USING SVM

In [12]:
model = SVC()
model.fit(train,train_label)
print(np.array(tv).reshape(1,-1))
model.predict(np.array(tv).reshape(1,-1))

[[1 1 0 0 1 0 0 0 0 0 0 0 0]]


array([0])